Add hooks for decorators
sola-st/DynaPyt pull request #76
Opened 2024-09-25 15:40 UTC by KeerthiVasudevan

2024-09-25 18:53 UTC, AryazE requested changes
Looks good!
Please address the comments and re-request the review.
Please also add a test with some builtin decorators.

2024-09-25 18:53 UTC, AryazE commented on src/dynapyt/analyses/TraceAll.py
> +        """
Add description of what the return value does.

2024-09-25 18:53 UTC, AryazE commented on tests/trace_single_hook/decorators/decorator_runtime_control_flow_events/analysis.py
Move this test to `manipulate_single_hook` directory.

2024-09-25 18:53 UTC, AryazE commented on tests/trace_single_hook/decorators/nested_decorator/program.py
Modify this test so that each enter and exit is different for each of the decorators. You can either rename one of the wrappers, or use the `wraps` decorator.

2024-09-26 10:36 UTC, KeerthiVasudevan commented on tests/trace_single_hook/decorators/decorator_runtime_control_flow_events/analysis.py
Can I move the similar test for with statement to this directory as well?

2024-09-26 21:17 UTC, AryazE commented on tests/trace_single_hook/decorators/decorator_runtime_control_flow_events/analysis.py
Not in this branch. You can create another pull request for moving those tests.

2024-09-26 21:19 UTC, AryazE approved these changes
LGTM, thanks!

2024-09-26 21:19 UTC, merged